** Bag of Words (BOW) **

In [52]:
# # Import requires libraries
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer



import re
import spacy

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression

import pandas as pd
import numpy as np

In [53]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [54]:
data = {
    "review": [
        "I absolutely love this phone! The camera quality is fantastic and battery lasts all day.",
        "Terrible experience. The screen broke within a week, and customer service was useless.",
        "Great value for money. Performance is smooth and build quality feels premium.",
        "The laptop overheats and the battery drains too fast. Very disappointed.",
        "Excellent sound quality and very comfortable to wear. Highly recommend these headphones!",
        "Worst product I’ve ever bought. It stopped working after two days.",
        "Amazing performance and display. Totally worth the price.",
        "Poor design and fragile build. I regret buying this item.",
        "Fast delivery and great packaging. The product works as expected.",
        "Customer support was unhelpful. Will not buy from this brand again."
    ],
    "sentiment": [
        "positive", "negative", "positive", "negative", "positive",
        "negative", "positive", "negative", "positive", "negative"
    ]
}

In [55]:
df=pd.DataFrame(data)
df.head()

                                              review sentiment
0  I absolutely love this phone! The camera quali...  positive
1  Terrible experience. The screen broke within a...  negative
2  Great value for money. Performance is smooth a...  positive
3  The laptop overheats and the battery drains to...  negative
4  Excellent sound quality and very comfortable t...  positive

In [56]:
def clean_text(text):
  text=text.lower()
  text=re.sub(r'[^a-zA-Z0-9\s]', '', text)
  text=' '.join([word for word in text.split() if word not in stopwords.words('english')])
  return text

In [57]:
df['clean_review']=df['review'].apply(clean_text)
df.head()

,review,sentiment,clean_review
0,I absolutely love this phone! The camera quali...,positive,absolutely love phone camera quality fantastic...
1,Terrible experience. The screen broke within a...,negative,terrible experience screen broke within week c...
2,Great value for money. Performance is smooth a...,positive,great value money performance smooth build qua...
3,The laptop overheats and the battery drains to...,negative,laptop overheats battery drains fast disappointed
4,Excellent sound quality and very comfortable t...,positive,excellent sound quality comfortable wear highl...

In [58]:
cv=CountVectorizer(max_features=20)
X=cv.fit_transform(df['clean_review']).toarray()
y=df['sentiment']
cv.get_feature_names_out()
bow_df=pd.DataFrame(X, columns=cv.get_feature_names_out())
bow_df.head()

,amazing,battery,bought,brand,build,buy,buying,camera,comfortable,customer,day,delivery,design,disappointed,display,fast,great,performance,product,quality
0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1
3,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0
4,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1

In [59]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [60]:
model=LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [61]:
# User Prediction
print('\nEnter yout review below :')
user_review=input('\nEnter your product review')

user_review=clean_text(user_review)
user_review_bow=cv.transform([user_review]).toarray()

user_sentiment=model.predict(user_review_bow)

print('\nClean Review',user_review)
print('\nPredicted Sentiment :', user_sentiment[0])

Enter yout review below :

Enter your product reviewbad customer service

Clean Review bad customer service

Predicted Sentiment : negative

Practice Exercise -One
input_text="Natural Language Processing is going to help you out in near future . You have 2 remember this!! for getting interview calls"
Do the following Tasks:
Spilts text into words/tokens (show the individual word token)
Clean Tokens (show clean token)
Remove Stop words (Show token after removing stop words)
Stemming (Show the words in their root forms)
Lemmatization (Show lemma words)

In [62]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [63]:
input_text="Natural Language Processing is going to help you out in near future . You have 2 remember this!! for getting interview calls"

In [64]:
tokens=word_tokenize(input_text)

tokens

['Natural',
 'Language',
 'Processing',
 'is',
 'going',
 'to',
 'help',
 'you',
 'out',
 'in',
 'near',
 'future',
 '.',
 'You',
 'have',
 '2',
 'remember',
 'this',
 '!',
 '!',
 'for',
 'getting',
 'interview',
 'calls']

In [65]:
clean_tokens=[re.sub('[^a-zA-Z]','',token.lower()) for token in tokens if token.isalpha()]
clean_tokens

['natural',
 'language',
 'processing',
 'is',
 'going',
 'to',
 'help',
 'you',
 'out',
 'in',
 'near',
 'future',
 'you',
 'have',
 'remember',
 'this',
 'for',
 'getting',
 'interview',
 'calls']

In [66]:
stop_words=set(stopwords.words('english'))
filtered_tokens=[token for token in clean_tokens if token not in stop_words]
# removes common less meaningful words
filtered_tokens

['natural',
 'language',
 'processing',
 'going',
 'help',
 'near',
 'future',
 'remember',
 'getting',
 'interview',
 'calls']

In [67]:
stemmer=PorterStemmer()
stemmed_tokens=[stemmer.stem(token) for token in filtered_tokens]

stemmed_tokens

['natur',
 'languag',
 'process',
 'go',
 'help',
 'near',
 'futur',
 'rememb',
 'get',
 'interview',
 'call']

In [68]:
lemmatizer=WordNetLemmatizer()
lemmatized_tokens=[lemmatizer.lemmatize(token) for token in filtered_tokens]

lemmatized_tokens

['natural',
 'language',
 'processing',
 'going',
 'help',
 'near',
 'future',
 'remember',
 'getting',
 'interview',
 'call']

In [72]:
tfidf=TfidfVectorizer()
tfidf_matrix=tfidf.fit_transform(lemmatized_tokens)
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 11 stored elements and shape (11, 11)>

In [73]:
df=pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf.get_feature_names_out())
df.head()

,call,future,getting,going,help,interview,language,natural,near,processing,remember
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

** TF-IDF Example 2 **

In [74]:
corpus=['Python developer required with strong coding skills',
        'Experience in REST API, Automation, Jenkins, Flask and Python',
        'Looking for machine learning engineer familiar with NLP, Supervised, Unsupervised and Deep Learning']

In [75]:
tfdif=TfidfVectorizer()

matrix=tfdif.fit_transform(corpus)
df=pd.DataFrame(matrix.toarray(), columns=tfdif.get_feature_names_out())
df.head()

,and,api,automation,coding,deep,developer,engineer,experience,familiar,flask,...,machine,nlp,python,required,rest,skills,strong,supervised,unsupervised,with
0,0.00000,0.000000,0.000000,0.403016,0.000000,0.403016,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.306504,0.403016,0.000000,0.403016,0.403016,0.000000,0.000000,0.306504
1,0.26629,0.350139,0.350139,0.000000,0.000000,0.000000,0.000000,0.350139,0.000000,0.350139,...,0.000000,0.000000,0.266290,0.000000,0.350139,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.20213,0.000000,0.000000,0.000000,0.265777,0.000000,0.265777,0.000000,0.265777,0.000000,...,0.265777,0.265777,0.000000,0.000000,0.000000,0.000000,0.000000,0.265777,0.265777,0.202130

In [76]:
print('n Top Weighted Teras')
print(df.mean().sort_values(ascending=False).head(10))

n Top Weighted Teras
python       0.190931
learning     0.177185
with         0.169545
and          0.156140
coding       0.134339
skills       0.134339
developer    0.134339
strong       0.134339
required     0.134339
in           0.116713
dtype: float64